name: Synchronizacja do SourceForge

on:
  push:
    branches: [ main ]

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Pobieranie kodu z GitHub
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Konfiguracja klucza SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SF_SSH_KEY }}
        name: id_ed25519
        known_hosts: 'dummy-value'
        if_key_exists: replace

    - name: Dodawanie SourceForge do Known Hosts
      run: |
        ssh-keyscan git.code.sf.net >> ~/.ssh/known_hosts

    - name: Push kodu do SourceForge
      run: |
        git remote add sf ssh://bartko5321@git.code.sf.net/p/arch-config/code
        git push sf main --force
